# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  skill_insert(
    data: {id: "11111111222233334444555555555558", authorClerkId: "user_3DWM8P6fWTFYHDmU3sd38XFarCJ", createdAt: "2026-05-10T12:52:58.695Z", description: "Identify render bottlenecks and optimize expensive client-side work.", installCommand: "npx skild add performance-tuner", promptConfig: "You are a professional performance optimization engineer", tags: ["ai-agient", "engineering"], title: "Performance Tuner", usageExample: "Review the code and optimize it"}
  )
}